language: scala
scala:
  - 2.12.6
before_install:
    # Decrypt credentials
  - openssl aes-256-cbc -K $encrypted_19aeec5168c7_key -iv $encrypted_19aeec5168c7_iv
    -in credentials.tar.gz.enc -out credentials.tar.gz -d

    # check gcloud-sdk
  - gcloud version || true

    # Authenticate with service account credentials
  - tar -xzf credentials.tar.gz
  - gcloud auth activate-service-account --key-file salt-service.json

  # move salt-service,json to conf/
  - mv ./salt-service.json ./conf/salt-service.json

  - chmod a+x ./scripts/install.sh
  - chmod a+x ./scripts/deploy-container.sh
install:
  - ./scripts/install.sh
scripts:
  - sbt test
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PWD
  - test $TRAVIS_BRANCH = "master" -o $TRAVIS_BRANCH = "develop" && sbt docker:publish && ./scripts/deploy-container.sh

